import bcrypt from 'bcryptjs';

const adminHash = bcrypt.hashSync('AAshfAAq123@', 10);
const userHash = bcrypt.hashSync('user123', 10);

export const inMemoryStore = {
  users: [
    {
      _id: 'user-admin',
      name: 'Portal Administrator',
      email: 'admin@scholarship.org',
      password: adminHash,
      role: 'admin',
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'user-admin-alias',
      name: 'Portal Administrator',
      email: 'admin',
      password: adminHash,
      role: 'admin',
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'user-student',
      name: 'Alexander Wright',
      email: 'user@scholarship.org',
      password: userHash,
      role: 'user',
      createdAt: new Date('2026-02-15'),
    },
  ],
  categories: [
    { _id: 'cat-1', name: 'Merit-based' },
    { _id: 'cat-2', name: 'Need-based' },
    { _id: 'cat-3', name: 'Government' },
    { _id: 'cat-4', name: 'University-specific' },
    { _id: 'cat-5', name: 'Research Fellowship' },
  ],
  countries: [
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
    'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
    'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica',
    'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
    'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
    'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guyana', 'Haiti',
    'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
    'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos',
    'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
    'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova',
    'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
    'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau',
    'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
    'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Saudi Arabia', 'Senegal',
    'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
    'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan',
    'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
    'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela',
    'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
  ].map((name, i) => ({ _id: `cnt-${i + 1}`, name })),
  scholarships: [
    {
      _id: 'sch-1',
      title: 'Chinese Government Scholarship (CSC) Silk Road Program',
      description: 'Fully funded Chinese Government Scholarship offering full tuition waiver, free university accommodation, comprehensive medical insurance, and a monthly living allowance for BS, MS, and PhD candidates across leading Chinese universities.',
      degreeLevel: 'MS',
      country: 'China',
      category: 'Government',
      fundingType: 'Full',
      deadline: new Date('2026-09-30'),
      officialLink: 'https://www.campuschina.org',
      applyLink: 'https://studyinchina.csc.edu.cn',
      image: '/uploads/csc-china.svg',
      status: 'open',
      createdAt: new Date('2026-03-01'),
      updatedAt: new Date('2026-03-01'),
    },
    {
      _id: 'sch-2',
      title: 'Fulbright Foreign Student Exchange Program USA',
      description: 'Prestigious full-funding grant for international graduate students, young professionals, and artists to study and conduct advanced research in the United States. Covers tuition, airfare, living stipend, and health insurance.',
      degreeLevel: 'MS',
      country: 'USA',
      category: 'Merit-based',
      fundingType: 'Full',
      deadline: new Date('2026-10-15'),
      officialLink: 'https://foreign.fulbrightonline.org',
      applyLink: 'https://foreign.fulbrightonline.org/apply',
      image: '/uploads/fulbright-usa.svg',
      status: 'open',
      createdAt: new Date('2026-03-05'),
      updatedAt: new Date('2026-03-05'),
    },
    {
      _id: 'sch-3',
      title: 'Finland Government National Excellence Grant',
      description: 'Generous tuition fee waivers and relocation stipends provided by top Finnish higher education institutions and the Finnish Ministry of Education for high-achieving international BS and MS students.',
      degreeLevel: 'BS',
      country: 'Finland',
      category: 'Government',
      fundingType: 'Partial',
      deadline: new Date('2026-08-31'),
      officialLink: 'https://www.studyinfinland.fi',
      applyLink: 'https://studyinfo.fi',
      image: '/uploads/finland-govt.svg',
      status: 'open',
      createdAt: new Date('2026-03-10'),
      updatedAt: new Date('2026-03-10'),
    },
    {
      _id: 'sch-4',
      title: 'Chevening UK Government Masters Scholarship',
      description: 'Chevening enables outstanding emerging leaders from all over the world to pursue a one-year Master degree in the UK. Includes full university tuition fees, monthly living allowance, return flights, and arrival allowance.',
      degreeLevel: 'MS',
      country: 'UK',
      category: 'Government',
      fundingType: 'Full',
      deadline: new Date('2026-11-02'),
      officialLink: 'https://www.chevening.org',
      applyLink: 'https://www.chevening.org/apply',
      image: '/uploads/chevening-uk.svg',
      status: 'open',
      createdAt: new Date('2026-03-12'),
      updatedAt: new Date('2026-03-12'),
    },
    {
      _id: 'sch-5',
      title: 'DAAD Masters & PhD Scholarships Germany',
      description: 'Fully funded scholarships offered by the German Academic Exchange Service for postgraduates from developing countries to pursue study and research in engineering, sciences, and public policy in Germany.',
      degreeLevel: 'PhD',
      country: 'Germany',
      category: 'Research Fellowship',
      fundingType: 'Full',
      deadline: new Date('2026-09-15'),
      officialLink: 'https://www.daad.de',
      applyLink: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
      image: '/uploads/daad-germany.svg',
      status: 'open',
      createdAt: new Date('2026-03-15'),
      updatedAt: new Date('2026-03-15'),
    },
    {
      _id: 'sch-6',
      title: 'Vanier Canada Graduate Doctoral Scholarships',
      description: 'Valued at $50,000 per year for three years, the Vanier CGS program attracts highly qualified doctoral students to Canadian universities in health, natural sciences, engineering, and humanities.',
      degreeLevel: 'PhD',
      country: 'Canada',
      category: 'Merit-based',
      fundingType: 'Full',
      deadline: new Date('2026-11-20'),
      officialLink: 'https://vanier.gc.ca',
      applyLink: 'https://vanier.gc.ca/en/home-accueil.html',
      image: '/uploads/vanier-canada.svg',
      status: 'open',
      createdAt: new Date('2026-03-18'),
      updatedAt: new Date('2026-03-18'),
    },
  ],
  blogs: [
    {
      _id: 'blog-1',
      title: 'How to Secure a Chinese Government Scholarship (CSC): Complete 2026 Guide',
      slug: 'how-to-secure-chinese-government-scholarship-csc-2026',
      content: `<p>Applying for the <strong>Chinese Government Scholarship (CSC)</strong> is one of the most rewarding opportunities for international students. CSC provides full tuition coverage, free dorms, and stipends up to 3,500 RMB/month.</p>
      <h3>Key Steps to Success:</h3>
      <ul>
        <li><strong>Find Target Universities:</strong> Research category A and category B institutions.</li>
        <li><strong>Contact Professors:</strong> Reach out early to obtain a Pre-Acceptance Letter.</li>
        <li><strong>Physical Examination Form:</strong> Ensure health checks are officially stamped by qualified medical officers.</li>
      </ul>`,
      coverImage: '/uploads/csc-china.svg',
      author: 'Dr. Sarah Chen',
      tags: ['China', 'CSC', 'Scholarship Guide', 'Fully Funded'],
      published: true,
      publishedAt: new Date('2026-03-01'),
      createdAt: new Date('2026-03-01'),
      updatedAt: new Date('2026-03-01'),
    },
    {
      _id: 'blog-2',
      title: 'Crafting a Winning Statement of Purpose for Top Global Universities',
      slug: 'crafting-winning-statement-of-purpose-global-universities',
      content: `<p>Your Statement of Purpose (SOP) is the heart of your scholarship application. Admissions committees read hundreds of essays daily, so clarity and authentic motivation stand out immediately.</p>
      <p>Focus on your research trajectory, specific university faculty matches, and long-term societal impact.</p>`,
      coverImage: '/uploads/default-blog.jpg',
      author: 'Marcus Vance',
      tags: ['SOP', 'Essay Writing', 'Admissions Tips'],
      published: true,
      publishedAt: new Date('2026-03-10'),
      createdAt: new Date('2026-03-10'),
      updatedAt: new Date('2026-03-10'),
    },
  ],
  ads: [
    {
      _id: 'ad-1',
      title: 'IELTS & TOEFL Prep Accelerator - 30% Student Discount',
      image: '/uploads/ad-ielts.svg',
      targetLink: 'https://www.e2language.com',
      placement: 'header',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-2',
      title: 'Global University Admission Review & Document Proofreading',
      image: '/uploads/ad-admission.svg',
      targetLink: 'https://www.topuniversities.com',
      placement: 'sidebar',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-3',
      title: 'Study in Europe & Asia - Free Application Consultation',
      image: '/uploads/csc-china.svg',
      targetLink: 'https://www.campuschina.org',
      placement: 'in-feed',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-4',
      title: 'Full Scholarship SOP & Proposal Writing Service - 50% Off',
      image: '/uploads/ad-admission.svg',
      targetLink: 'https://www.daad.de',
      placement: 'scholarship-detail-top',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-5',
      title: 'Certified Translation & Document Attestation for Visa',
      image: '/uploads/csc-china.svg',
      targetLink: 'https://www.chevening.org',
      placement: 'scholarship-detail-bottom',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-6',
      title: 'Join Premier Global Study Network & Alumni Club',
      image: '/uploads/ad-ielts.svg',
      targetLink: 'https://www.study.eu',
      placement: 'popup',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-7',
      title: 'International Student Visa & Health Insurance Partner',
      image: '/uploads/ad-admission.svg',
      targetLink: 'https://www.topuniversities.com',
      placement: 'blog-sidebar',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-8',
      title: 'Global Educational Travel & Flight Discounts for Students',
      image: '/uploads/csc-china.svg',
      targetLink: 'https://www.campuschina.org',
      placement: 'footer',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-9',
      title: 'Professional Resume & Study Plan Writing Consultation',
      image: '/uploads/ad-ielts.svg',
      targetLink: 'https://www.e2language.com',
      placement: 'about-page',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-10',
      title: 'Global University Admissions Support Hotline 2026',
      image: '/uploads/ad-admission.svg',
      targetLink: 'https://www.topuniversities.com',
      placement: 'contact-page',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
  ],
  contactInquiries: [
    {
      _id: 'inq-1',
      name: 'Muhammad Imran',
      email: 'imran.student@gmail.com',
      phone: '+923001234567',
      subject: 'CSC Scholarship Recommendation Letters Inquiry',
      inquiryType: 'CSC / China Scholarship Inquiry',
      message: 'Respected Sir, I want guidance regarding professor acceptance letters and CSC agency number for Harbin Institute of Technology.',
      status: 'pending',
      createdAt: new Date('2026-07-27T10:00:00Z'),
    },
  ],
  subscribers: [
    {
      _id: 'sub-1',
      email: 'techhub905@gmail.com',
      status: 'active',
      subscribedAt: new Date('2026-01-15'),
    },
    {
      _id: 'sub-2',
      email: 'student.scholarships@gmail.com',
      status: 'active',
      subscribedAt: new Date('2026-02-01'),
    }
  ],
  notificationLogs: [
    {
      _id: 'notif-1',
      scholarshipTitle: 'Chinese Government Scholarship (CSC) Silk Road Program',
      recipientCount: 2,
      recipients: ['techhub905@gmail.com', 'student.scholarships@gmail.com'],
      sentAt: new Date('2026-07-28T01:00:00Z'),
      status: 'delivered'
    }
  ],
  settings: {
    _id: 'settings-global-1',
    siteName: 'Global Scholarship Portal',
    siteLink: 'https://scholarship-portal.vercel.app',
    contactEmail: 'techhub905@gmail.com',
    whatsapp: '+92-346-3079238',
    whatsappMessage: 'Hello! I need scholarship application guidance and help.',
    github: 'https://github.com/techhub905',
    snapchat: 'https://snapchat.com/add/scholarship_portal',
    instagram: 'https://instagram.com/scholarship_portal',
    telegram: 'https://t.me/scholarship_portal',
    facebook: 'https://facebook.com/scholarshipportal',
    twitter: 'https://x.com/scholarship_app',
    linkedin: 'https://linkedin.com/company/scholarship-portal',
    youtube: 'https://youtube.com/@scholarship_portal',
    customLinks: [
      {
        platformName: 'Discord Support',
        url: 'https://discord.gg/scholarship',
        icon: 'message-square',
      },
      {
        platformName: 'TikTok Tips',
        url: 'https://tiktok.com/@scholarship_tips',
        icon: 'video',
      },
    ],
    updatedAt: new Date(),
  },
};
