import bcrypt from 'bcryptjs';

const adminHash = bcrypt.hashSync('AAshfAAq123@', 10);
const userHash = bcrypt.hashSync('user123', 10);

export const inMemoryStore = {
  users: [
    {
      _id: 'user-admin',
      name: 'Portal Administrator',
      email: 'admin@scholarship.org',
      password: adminHash,
      role: 'admin',
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'user-admin-alias',
      name: 'Portal Administrator',
      email: 'admin',
      password: adminHash,
      role: 'admin',
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'user-student',
      name: 'Alexander Wright',
      email: 'user@scholarship.org',
      password: userHash,
      role: 'user',
      createdAt: new Date('2026-02-15'),
    },
  ],
  categories: [
    { _id: 'cat-1', name: 'Merit-based' },
    { _id: 'cat-2', name: 'Need-based' },
    { _id: 'cat-3', name: 'Government' },
    { _id: 'cat-4', name: 'University-specific' },
    { _id: 'cat-5', name: 'Research Fellowship' },
  ],
  countries: [
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
    'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
    'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica',
    'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
    'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
    'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guyana', 'Haiti',
    'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
    'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos',
    'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
    'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova',
    'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
    'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau',
    'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
    'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Saudi Arabia', 'Senegal',
    'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
    'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan',
    'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
    'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela',
    'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
  ].map((name, i) => ({ _id: `cnt-${i + 1}`, name })),
  scholarships: [
    {
      _id: 'sch-1',
      opportunityType: 'scholarship',
      title: 'Chinese Government Scholarship (CSC) Silk Road Program',
      hostUniversity: 'Tsinghua University / CSC Host Institutions in China',
      description: 'Fully funded Chinese Government Scholarship offering full tuition waiver, free university accommodation, comprehensive medical insurance, and a monthly living allowance for BS, MS, and PhD candidates across leading Chinese universities.',
      degreeLevel: 'MS',
      country: 'China',
      category: 'Government',
      fundingType: 'Full',
      financialCoverage: 'Full Tuition Waiver + RMB 3,000–3,500/month Living Allowance + Free On-Campus Dormitory + Comprehensive Medical Insurance',
      eligibilityCriteria: '1. Non-Chinese national in good physical and mental health\n2. Bachelor or Master degree holder (Under 35 for Masters, Under 40 for PhD)\n3. HSK 4+ for Chinese taught programs or IELTS 6.0+ / TOEFL 80+ for English taught programs\n4. Strong academic performance and research proposal',
      requiredDocuments: '1. CSC Online Application Form\n2. Notarized Highest Diploma & Official Academic Transcripts\n3. Study Plan or Research Proposal (min 800 words)\n4. Two Recommendation Letters from Professors\n5. Foreigner Physical Examination Form\n6. Non-Criminal Record Certificate (Police Clearance)',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-09-30'),
      officialLink: 'https://www.campuschina.org',
      applyLink: 'https://studyinchina.csc.edu.cn',
      image: '/uploads/csc-china.svg',
      status: 'open',
      createdAt: new Date('2026-03-01'),
      updatedAt: new Date('2026-03-01'),
    },
    {
      _id: 'sch-2',
      opportunityType: 'scholarship',
      title: 'Fulbright Foreign Student Exchange Program USA',
      hostUniversity: 'Partner Universities & Graduate Institutions across the United States',
      description: 'Prestigious full-funding grant for international graduate students, young professionals, and artists to study and conduct advanced research in the United States. Covers tuition, airfare, living stipend, and health insurance.',
      degreeLevel: 'MS',
      country: 'USA',
      category: 'Merit-based',
      fundingType: 'Full',
      financialCoverage: 'Full Tuition Coverage + Monthly Living Allowance + Roundtrip International Airfare + Health & Accident Insurance + J-1 Visa Sponsorship',
      eligibilityCriteria: '1. International applicant residing outside the US at time of application\n2. Completed bachelor degree with strong academic achievement\n3. Demonstrated leadership capability and commitment to community service\n4. TOEFL iBT 80+ or IELTS 6.5+ band score',
      requiredDocuments: '1. Fulbright Online Application\n2. Personal Statement & Academic Study Objectives\n3. Three Official Confidential Letters of Recommendation\n4. Certified University Transcripts & Degree Certificates\n5. Standardized Test Scores (GRE/GMAT if required)',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-10-15'),
      officialLink: 'https://foreign.fulbrightonline.org',
      applyLink: 'https://foreign.fulbrightonline.org/apply',
      image: '/uploads/fulbright-usa.svg',
      status: 'open',
      createdAt: new Date('2026-03-05'),
      updatedAt: new Date('2026-03-05'),
    },
    {
      _id: 'sch-3',
      opportunityType: 'scholarship',
      title: 'Finland Government National Excellence Grant',
      hostUniversity: 'Aalto University, University of Helsinki & Finnish Higher Education Institutes',
      description: 'Generous tuition fee waivers and relocation stipends provided by top Finnish higher education institutions and the Finnish Ministry of Education for high-achieving international BS and MS students.',
      degreeLevel: 'BS',
      country: 'Finland',
      category: 'Government',
      fundingType: 'Partial',
      financialCoverage: '100% Tuition Fee Waiver + EUR 5,000 Relocation Grant for First Academic Year',
      eligibilityCriteria: '1. Non-EU/EEA international applicant applying to eligible Bachelor or Master program in Finland\n2. Outstanding secondary school or undergraduate academic records\n3. English proficiency certificate (IELTS 6.5 or TOEFL 92)',
      requiredDocuments: '1. Joint Application Form via Studyinfo.fi\n2. Copy of Passport / National ID\n3. Educational Certificates & Official Grade Transcripts\n4. Motivation Letter',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-08-31'),
      officialLink: 'https://www.studyinfinland.fi',
      applyLink: 'https://studyinfo.fi',
      image: '/uploads/finland-govt.svg',
      status: 'open',
      createdAt: new Date('2026-03-10'),
      updatedAt: new Date('2026-03-10'),
    },
    {
      _id: 'sch-4',
      opportunityType: 'scholarship',
      title: 'Chevening UK Government Masters Scholarship',
      hostUniversity: 'University of Oxford, Cambridge, Imperial College & All UK Universities',
      description: 'Chevening enables outstanding emerging leaders from all over the world to pursue a one-year Master degree in the UK. Includes full university tuition fees, monthly living allowance, return flights, and arrival allowance.',
      degreeLevel: 'MS',
      country: 'UK',
      category: 'Government',
      fundingType: 'Full',
      financialCoverage: 'Full University Tuition Fees + Monthly Living Stipend + Economy Class Return Flights + Arrival & Excess Baggage Allowance',
      eligibilityCriteria: '1. Citizen of a Chevening-eligible country\n2. Undergraduate degree that qualifies for UK Master entry (2:1 equivalent)\n3. Minimum 2 years of work experience (equivalent to 2,800 hours)\n4. Apply to 3 eligible UK university courses and receive an unconditional offer',
      requiredDocuments: '1. Chevening Online Application Form\n2. Four Essay Responses (Leadership, Networking, Study in UK, Career Plan)\n3. Two Reference Letters\n4. Passport Copy & Academic Transcripts\n5. Unconditional Offer Letter from UK University',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-11-02'),
      officialLink: 'https://www.chevening.org',
      applyLink: 'https://www.chevening.org/apply',
      image: '/uploads/chevening-uk.svg',
      status: 'open',
      createdAt: new Date('2026-03-12'),
      updatedAt: new Date('2026-03-12'),
    },
    {
      _id: 'sch-5',
      opportunityType: 'scholarship',
      title: 'DAAD Masters & PhD Scholarships Germany',
      hostUniversity: 'TU Munich, RWTH Aachen, Heidelberg University & German Public Universities',
      description: 'Fully funded scholarships offered by the German Academic Exchange Service for postgraduates from developing countries to pursue study and research in engineering, sciences, and public policy in Germany.',
      degreeLevel: 'PhD',
      country: 'Germany',
      category: 'Research Fellowship',
      fundingType: 'Full',
      financialCoverage: 'EUR 934/month for Masters or EUR 1,200/month for PhD Candidates + Health Insurance + Travel Allowance + Family & Research Grants',
      eligibilityCriteria: '1. Bachelor or Master degree completed within the last 6 years\n2. At least 2 years of professional work experience in relevant field\n3. Proof of English or German language proficiency depending on chosen program',
      requiredDocuments: '1. DAAD Application Form\n2. Signed CV (Europass format)\n3. Hand-signed Letter of Motivation\n4. Recommendation Letter from Employer / Senior Professor\n5. Certified Diplomas & Transcripts',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-09-15'),
      officialLink: 'https://www.daad.de',
      applyLink: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
      image: '/uploads/daad-germany.svg',
      status: 'open',
      createdAt: new Date('2026-03-15'),
      updatedAt: new Date('2026-03-15'),
    },
    {
      _id: 'sch-6',
      opportunityType: 'scholarship',
      title: 'Vanier Canada Graduate Doctoral Scholarships',
      hostUniversity: 'University of Toronto, UBC, McGill & Canadian Partner Universities',
      description: 'Valued at $50,000 per year for three years, the Vanier CGS program attracts highly qualified doctoral students to Canadian universities in health, natural sciences, engineering, and humanities.',
      degreeLevel: 'PhD',
      country: 'Canada',
      category: 'Merit-based',
      fundingType: 'Full',
      financialCoverage: 'CAD $50,000 per year for 3 years of doctoral research',
      eligibilityCriteria: '1. Nominated by a Canadian university with a Vanier CGS quota\n2. Pursuing first doctoral degree (including joint MA/PhD or MD/PhD)\n3. Demonstrated high academic achievement, research potential, and leadership skills',
      requiredDocuments: '1. ResearchNet Online Application\n2. Common CV (CCV)\n3. Research Proposal (max 2 pages)\n4. Two Referee Assessment Reports\n5. Leadership Statement',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-11-20'),
      officialLink: 'https://vanier.gc.ca',
      applyLink: 'https://vanier.gc.ca/en/home-accueil.html',
      image: '/uploads/vanier-canada.svg',
      status: 'open',
      createdAt: new Date('2026-03-18'),
      updatedAt: new Date('2026-03-18'),
    },
    // INTERNSHIPS
    {
      _id: 'int-1',
      opportunityType: 'internship',
      title: 'CERN Summer Student Internship Program',
      hostUniversity: 'European Organization for Nuclear Research (CERN), Geneva',
      description: 'Fully funded 8 to 13-week summer internship in Switzerland for undergraduate and master students in physics, engineering, computer science, or mathematics. Includes living allowance and travel.',
      degreeLevel: 'BS',
      country: 'Switzerland',
      category: 'Research Fellowship',
      fundingType: 'Full',
      financialCoverage: 'CHF 90/day living allowance + Travel allowance + Health Insurance + On-site accommodation assistance',
      eligibilityCriteria: '1. Enrolled in Bachelor or Master degree program at time of internship\n2. Completed at least 3 years of full-time university studies\n3. Good knowledge of English or French',
      requiredDocuments: '1. Academic Transcript of Records\n2. Updated CV\n3. Two Reference Letters\n4. Motivation Letter describing research interests',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-10-30'),
      officialLink: 'https://home.cern',
      applyLink: 'https://careers.cern/summer-students',
      image: '/uploads/cern-switzerland.svg',
      status: 'open',
      createdAt: new Date('2026-03-20'),
      updatedAt: new Date('2026-03-20'),
    },
    {
      _id: 'int-2',
      opportunityType: 'internship',
      title: 'World Bank Group Paid International Internship',
      hostUniversity: 'World Bank Headquarters, Washington D.C. & Country Offices',
      description: 'Paid practical internship for graduate students seeking hands-on experience in global development, economics, finance, public health, and social sciences.',
      degreeLevel: 'MS',
      country: 'USA',
      category: 'Government',
      fundingType: 'Full',
      financialCoverage: 'Hourly Paid Salary (USD $25–35/hr) + Airfare travel allowance up to USD $3,000 for overseas candidates',
      eligibilityCriteria: '1. Enrolled in full-time Master or PhD graduate program\n2. Fluent in English (knowledge of French/Spanish/Arabic is an asset)\n3. Strong analytical and quantitative skills',
      requiredDocuments: '1. World Bank Online Application Form\n2. Curriculum Vitae (CV)\n3. Statement of Interest & Research Focus\n4. Proof of Enrollment in Graduate Degree Program',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-11-15'),
      officialLink: 'https://www.worldbank.org',
      applyLink: 'https://www.worldbank.org/en/about/careers/programs-and-internships/internship',
      image: '/uploads/worldbank-usa.svg',
      status: 'open',
      createdAt: new Date('2026-03-22'),
      updatedAt: new Date('2026-03-22'),
    },
    {
      _id: 'int-3',
      opportunityType: 'internship',
      title: 'Max Planck Institute Scientific Research Summer Internship',
      hostUniversity: 'Max Planck Society Institutes across Germany',
      description: 'Fully funded summer research internship for outstanding international bachelor and master students in biology, chemistry, computer science, and astrophysics.',
      degreeLevel: 'BS',
      country: 'Germany',
      category: 'Research Fellowship',
      fundingType: 'Full',
      financialCoverage: 'EUR 800–1,000/month stipend + Free student housing + Travel flight expenses reimbursed',
      eligibilityCriteria: '1. Enrolled in Bachelor or Master degree in natural sciences or computer science\n2. Strong academic records with passion for scientific research\n3. Fluency in written and spoken English',
      requiredDocuments: '1. Online Application Form\n2. Official University Grade Transcripts\n3. Resume / CV\n4. Motivation Statement\n5. Recommendation Letter from Academic Advisor',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-09-25'),
      officialLink: 'https://www.mpg.de/en',
      applyLink: 'https://www.mpg.de/en/career/internships',
      image: '/uploads/daad-germany.svg',
      status: 'open',
      createdAt: new Date('2026-03-25'),
      updatedAt: new Date('2026-03-25'),
    },
    // FELLOWSHIPS
    {
      _id: 'fel-1',
      opportunityType: 'fellowship',
      title: 'Rotary Peace World Fellowship Program',
      hostUniversity: 'University of Queensland, International Christian University & Duke University',
      description: 'Fully funded Rotary Peace Fellowship for leaders committed to conflict resolution and international peacebuilding. Offers Master degree or professional certificate programs.',
      degreeLevel: 'MS',
      country: 'Australia',
      category: 'Merit-based',
      fundingType: 'Full',
      financialCoverage: 'Full Tuition & University Fees + Room & Board + Roundtrip Transportation + Internship & Fieldwork Expenses',
      eligibilityCriteria: '1. Bachelor degree with strong academic record\n2. Minimum 3 years of relevant work experience in peace or development\n3. English proficiency and demonstrated leadership capabilities',
      requiredDocuments: '1. Rotary Fellowship Application\n2. Resume / CV\n3. Two Letters of Recommendation\n4. Essays on Peace & Conflict Resolution Objectives\n5. Academic Transcripts',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-10-01'),
      officialLink: 'https://www.rotary.org',
      applyLink: 'https://www.rotary.org/en/our-programs/peace-fellowships',
      image: '/uploads/rotary-peace.svg',
      status: 'open',
      createdAt: new Date('2026-03-26'),
      updatedAt: new Date('2026-03-26'),
    },
    {
      _id: 'fel-2',
      opportunityType: 'fellowship',
      title: 'Humboldt Research Fellowship for Postdoctoral Researchers',
      hostUniversity: 'Alexander von Humboldt Foundation & Host Universities in Germany',
      description: 'Allows high-spec postdocs and experienced researchers of all nationalities to conduct long-term research (6-24 months) in Germany with a host professor.',
      degreeLevel: 'PhD',
      country: 'Germany',
      category: 'Research Fellowship',
      fundingType: 'Full',
      financialCoverage: 'EUR 2,670/month stipend for postdocs or EUR 3,170/month for experienced researchers + Family allowance + Intensive German language course',
      eligibilityCriteria: '1. Doctorate (PhD) completed within the last 4 years\n2. Academic publications in peer-reviewed journals\n3. Agreed research plan with host institute in Germany',
      requiredDocuments: '1. Detailed Research Outline (min 5 pages)\n2. Publication List & Selected Papers\n3. Recommendation Letters from Academic Referees\n4. Host Confirmation Letter',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-12-01'),
      officialLink: 'https://www.humboldt-foundation.de',
      applyLink: 'https://www.humboldt-foundation.de/en/apply/sponsorship-programmes/humboldt-research-fellowship',
      image: '/uploads/daad-germany.svg',
      status: 'open',
      createdAt: new Date('2026-03-28'),
      updatedAt: new Date('2026-03-28'),
    },
    // SEMINARS
    {
      _id: 'sem-1',
      opportunityType: 'seminar',
      title: 'World Youth Forum & International Leadership Seminar',
      hostUniversity: 'World Youth Forum Organization, Sharm El Sheikh',
      description: 'Fully funded international summit bringing together young leaders, policymakers, researchers, and innovators from 150+ countries for panel discussions, workshops, and cross-cultural exchange.',
      degreeLevel: 'BS',
      country: 'Egypt',
      category: 'Government',
      fundingType: 'Full',
      financialCoverage: '100% Covered International Return Flight Tickets + 5-Star Hotel Accommodation + All Meals & Local Transportation + Summit Materials',
      eligibilityCriteria: '1. Open to youth aged 18–35 from all countries and academic backgrounds\n2. Passion for international affairs, youth empowerment, or technology\n3. English communication skills',
      requiredDocuments: '1. Online Delegate Application Form\n2. Copy of Passport\n3. High-resolution Headshot Photo\n4. Short Essay response (max 300 words)',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-09-10'),
      officialLink: 'https://wyfegypt.com',
      applyLink: 'https://wyfegypt.com/apply',
      image: '/uploads/wyf-egypt.svg',
      status: 'open',
      createdAt: new Date('2026-03-29'),
      updatedAt: new Date('2026-03-29'),
    },
    {
      _id: 'sem-2',
      opportunityType: 'seminar',
      title: 'Asia-Europe Foundation Young Leaders Summit & Conference',
      hostUniversity: 'ASEF Secretariat & Nanyang Technological University, Singapore',
      description: 'Fully funded youth summit focusing on artificial intelligence, climate action, and sustainable development goals for students and young professionals across Asia and Europe.',
      degreeLevel: 'MS',
      country: 'Singapore',
      category: 'University-specific',
      fundingType: 'Full',
      financialCoverage: 'Full Travel Subsidy + Shared Hotel Accommodation + Meals & Conference Registration Fee Covered',
      eligibilityCriteria: '1. Citizen of ASEF member countries in Asia and Europe\n2. Aged 18–30 with active engagement in youth organizations or social enterprise',
      requiredDocuments: '1. ASEF Online Application\n2. Professional CV\n3. Video Statement of Purpose (90 seconds)\n4. Academic or Work Reference',
      applicationFee: 'Free / No Application Fee',
      deadline: new Date('2026-08-20'),
      officialLink: 'https://asef.org',
      applyLink: 'https://asef.org/projects/asef-young-leaders-summit/',
      image: '/uploads/asef-singapore.svg',
      status: 'open',
      createdAt: new Date('2026-03-30'),
      updatedAt: new Date('2026-03-30'),
    },
  ],
  blogs: [
    {
      _id: 'blog-1',
      title: 'How to Secure a Chinese Government Scholarship (CSC): Complete 2026 Guide',
      slug: 'how-to-secure-chinese-government-scholarship-csc-2026',
      content: `<p>Applying for the <strong>Chinese Government Scholarship (CSC)</strong> is one of the most rewarding opportunities for international students. CSC provides full tuition coverage, free dorms, and stipends up to 3,500 RMB/month.</p>
      <h3>Key Steps to Success:</h3>
      <ul>
        <li><strong>Find Target Universities:</strong> Research category A and category B institutions.</li>
        <li><strong>Contact Professors:</strong> Reach out early to obtain a Pre-Acceptance Letter.</li>
        <li><strong>Physical Examination Form:</strong> Ensure health checks are officially stamped by qualified medical officers.</li>
      </ul>`,
      coverImage: '/uploads/csc-china.svg',
      author: 'Dr. Sarah Chen',
      tags: ['China', 'CSC', 'Scholarship Guide', 'Fully Funded'],
      published: true,
      publishedAt: new Date('2026-03-01'),
      createdAt: new Date('2026-03-01'),
      updatedAt: new Date('2026-03-01'),
    },
    {
      _id: 'blog-2',
      title: 'Crafting a Winning Statement of Purpose for Top Global Universities',
      slug: 'crafting-winning-statement-of-purpose-global-universities',
      content: `<p>Your Statement of Purpose (SOP) is the heart of your scholarship application. Admissions committees read hundreds of essays daily, so clarity and authentic motivation stand out immediately.</p>
      <p>Focus on your research trajectory, specific university faculty matches, and long-term societal impact.</p>`,
      coverImage: '/uploads/default-blog.jpg',
      author: 'Marcus Vance',
      tags: ['SOP', 'Essay Writing', 'Admissions Tips'],
      published: true,
      publishedAt: new Date('2026-03-10'),
      createdAt: new Date('2026-03-10'),
      updatedAt: new Date('2026-03-10'),
    },
  ],
  ads: [
    {
      _id: 'ad-1',
      title: 'IELTS & TOEFL Prep Accelerator - 30% Student Discount',
      image: '/uploads/ad-ielts.svg',
      targetLink: 'https://www.e2language.com',
      placement: 'header',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-2',
      title: 'Global University Admission Review & Document Proofreading',
      image: '/uploads/ad-admission.svg',
      targetLink: 'https://www.topuniversities.com',
      placement: 'sidebar',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-3',
      title: 'Study in Europe & Asia - Free Application Consultation',
      image: '/uploads/csc-china.svg',
      targetLink: 'https://www.campuschina.org',
      placement: 'in-feed',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-4',
      title: 'Full Scholarship SOP & Proposal Writing Service - 50% Off',
      image: '/uploads/ad-admission.svg',
      targetLink: 'https://www.daad.de',
      placement: 'scholarship-detail-top',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-5',
      title: 'Certified Translation & Document Attestation for Visa',
      image: '/uploads/csc-china.svg',
      targetLink: 'https://www.chevening.org',
      placement: 'scholarship-detail-bottom',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-6',
      title: 'Join Premier Global Study Network & Alumni Club',
      image: '/uploads/ad-ielts.svg',
      targetLink: 'https://www.study.eu',
      placement: 'popup',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-7',
      title: 'International Student Visa & Health Insurance Partner',
      image: '/uploads/ad-admission.svg',
      targetLink: 'https://www.topuniversities.com',
      placement: 'blog-sidebar',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-8',
      title: 'Global Educational Travel & Flight Discounts for Students',
      image: '/uploads/csc-china.svg',
      targetLink: 'https://www.campuschina.org',
      placement: 'footer',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-9',
      title: 'Professional Resume & Study Plan Writing Consultation',
      image: '/uploads/ad-ielts.svg',
      targetLink: 'https://www.e2language.com',
      placement: 'about-page',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
    {
      _id: 'ad-10',
      title: 'Global University Admissions Support Hotline 2026',
      image: '/uploads/ad-admission.svg',
      targetLink: 'https://www.topuniversities.com',
      placement: 'contact-page',
      active: true,
      startDate: new Date('2026-01-01'),
      endDate: null,
      createdAt: new Date('2026-01-01'),
    },
  ],
  contactInquiries: [
    {
      _id: 'inq-1',
      name: 'Muhammad Imran',
      email: 'imran.student@gmail.com',
      phone: '+923001234567',
      subject: 'CSC Scholarship Recommendation Letters Inquiry',
      inquiryType: 'CSC / China Scholarship Inquiry',
      message: 'Respected Sir, I want guidance regarding professor acceptance letters and CSC agency number for Harbin Institute of Technology.',
      status: 'pending',
      createdAt: new Date('2026-07-27T10:00:00Z'),
    },
  ],
  subscribers: [
    {
      _id: 'sub-1',
      email: 'techhub905@gmail.com',
      status: 'active',
      subscribedAt: new Date('2026-01-15'),
    },
    {
      _id: 'sub-2',
      email: 'student.scholarships@gmail.com',
      status: 'active',
      subscribedAt: new Date('2026-02-01'),
    }
  ],
  notificationLogs: [
    {
      _id: 'notif-1',
      scholarshipTitle: 'Chinese Government Scholarship (CSC) Silk Road Program',
      recipientCount: 2,
      recipients: ['techhub905@gmail.com', 'student.scholarships@gmail.com'],
      sentAt: new Date('2026-07-28T01:00:00Z'),
      status: 'delivered'
    }
  ],
  settings: {
    _id: 'settings-global-1',
    siteName: 'Global Scholarship Portal',
    siteLink: 'https://scholarship-portal.vercel.app',
    contactEmail: 'techhub905@gmail.com',
    whatsapp: '+92-346-3079238',
    whatsappMessage: 'Hello! I need scholarship application guidance and help.',
    github: 'https://github.com/techhub905',
    snapchat: 'https://snapchat.com/add/scholarship_portal',
    instagram: 'https://instagram.com/scholarship_portal',
    telegram: 'https://t.me/scholarship_portal',
    facebook: 'https://facebook.com/scholarshipportal',
    twitter: 'https://x.com/scholarship_app',
    linkedin: 'https://linkedin.com/company/scholarship-portal',
    youtube: 'https://youtube.com/@scholarship_portal',
    customLinks: [
      {
        platformName: 'Discord Support',
        url: 'https://discord.gg/scholarship',
        icon: 'message-square',
      },
      {
        platformName: 'TikTok Tips',
        url: 'https://tiktok.com/@scholarship_tips',
        icon: 'video',
      },
    ],
    updatedAt: new Date(),
  },
};
