services:
  - type: web
    name: scholarship-portal-fullstack
    env: node
    plan: free
    region: singapore
    buildCommand: "npm run clean && npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: "/api/health"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RUN_STANDALONE
        value: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
